# Generated by Django 2.2.5 on 2019-11-19 08:31

# 导入Django迁移模块和模型字段模块
from django.db import migrations, models

# 定义迁移类，继承自Django的Migration基类，用于描述数据库结构的变更
class Migration(migrations.Migration):

    # initial=True表示这是一个初始迁移（首次创建模型对应的数据库表）
    initial = True

    # dependencies用于声明当前迁移依赖的其他迁移文件
    # 空列表表示该迁移没有依赖（通常初始迁移无依赖）
    dependencies = [
    ]

    # operations列表定义了当前迁移要执行的具体数据库操作
    operations = [
        # 创建一个名为'Profession'的数据库表
        migrations.CreateModel(
            name='Profession',  # 模型名称
            fields=[    # 定义模型的字段
                #id字段：自动增长的主键，Django默认会为模型添加该字段，这里显式定义
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # type1字段：字符类型，最大长度128
                ('type1', models.CharField(max_length=128)),
                # type2字段：字符类型，最大长度128
                ('type2', models.CharField(max_length=128)),
                # profession_name字段：字符类型，最大长度256
                ('profession_name', models.CharField(max_length=256)),
            ],
            options={# 模型的元数据选项
                'verbose_name': '专业信息', #模型的单数名称
                'verbose_name_plural': '专业信息',  #模型的复数名称
                'ordering': ['id'], #默认排序方式，按id字段升序排列
            },
        ),
    ]
