# Generated by Django 2.2.5 on 2019-11-19 09:20

# 导入Django迁移模块和模型字段模块
from django.db import migrations, models

# 定义迁移类，继承自Django的Migration基类，用于描述数据库结构的变更
class Migration(migrations.Migration):

    # dependencies用于声明当前迁移依赖的其他迁移文件
    dependencies = [
        ('recommend_profession', '0001_initial'),   # 依赖于0001_initial迁移文件
    ]

    # operations列表定义了当前迁移要执行的具体数据库操作
    operations = [
            # 创建一个名为'Profession_Hot'的数据库表
        migrations.CreateModel(
            name='Profession_Hot',  # 模型名称
            # 定义模型的字段
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # id字段：自动增长的主键，Django默认会为模型添加该字段，这里显式定义
                ('profession_name', models.CharField(max_length=256)),  # profession_name字段：字符类型，最大长度256
                ('profession_hot', models.CharField(max_length=256)),   # profession_hot字段：字符类型，最大长度256
                ('profession_type', models.CharField(max_length=256)),  # profession_type字段：字符类型，最大长度256
            ],
        ),
    ]
