# Generated by Django 2.2.5 on 2019-11-25 02:13

# 导入Django迁移模块和模型字段模块
from django.db import migrations, models

# 定义迁移类，继承自Django的Migration基类，用于描述数据库结构的变更
class Migration(migrations.Migration):

    # dependencies用于声明当前迁移依赖的其他迁移文件
    dependencies = [
        ('recommend_profession', '0002_profession_hot'),   # 依赖于0002_profession_hot迁移文件
    ]

    # operations列表定义了当前迁移要执行的具体数据库操作
    operations = [
        # 删除名为'Profession_Hot'的数据库表
        migrations.DeleteModel(
            name='Profession_Hot',  # 模型名称
        ),
           
         # 向名为'Profession'的数据库表添加新字段
        migrations.AddField(
            model_name='profession',    # 模型名称
            name='profession_hot',  # 新字段名称
            field=models.CharField(blank=True, max_length=256, null=True),  # 新字段类型为字符类型，最大长度256，允许为空值和空字符串
        ),

        # 向名为'Profession'的数据库表添加新字段
        migrations.AddField(
            model_name='profession',    # 模型名称
            name='profession_type', # 新字段名称
            field=models.CharField(blank=True, max_length=256, null=True),  # 新字段类型为字符类型，最大长度256，允许为空值和空字符串
        ),
    ]
