# Generated by Django 2.2.5 on 2019-12-09 03:48

# 导入Django迁移模块和模型字段模块
from django.db import migrations, models

# 定义迁移类，继承自Django的Migration基类，用于描述数据库结构的变更
class Migration(migrations.Migration):

    # dependencies用于声明当前迁移依赖的其他迁移文件
    dependencies = [
        ('recommend_profession', '0003_auto_20191125_1013'),    # 依赖于0003_auto_20191125_1013迁移文件
    ]

    # operations列表定义了当前迁移要执行的具体数据库操作
    operations = [
        # 向名为'Profession'的数据库表添加新字段
        migrations.AddField(
            model_name='profession',    # 模型名称
            name='show1',   # 新字段名称
            field=models.CharField(default='', max_length=2048),    # 新字段类型为字符类型，最大长度2048，默认值为空字符串
            preserve_default=False, # 不保留默认值
        ),

        # 向名为'Profession'的数据库表添加新字段
        migrations.AddField(
            model_name='profession',    # 模型名称
            name='show2',   # 新字段名称
            field=models.CharField(default='', max_length=2048),    # 新字段类型为字符类型，最大长度2048，默认值为空字符串
            preserve_default=False, # 不保留默认值
        ),

        # 向名为'Profession'的数据库表添加新字段
        migrations.AddField(
            model_name='profession',    # 模型名称
            name='show3',   # 新字段名称
            field=models.CharField(default='', max_length=2048),    # 新字段类型为字符类型，最大长度2048，默认值为空字符串
            preserve_default=False, # 不保留默认值
        ),
    ]
