# Generated by Django 5.2.6 on 2025-12-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_profession", "0005_profession_trend"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="professiontrend",
            unique_together={("profession_name", "year")},
        ),
    ]
