# Generated by Django 5.2.6 on 2025-12-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_profession", "0006_alter_professiontrend_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfessionTrend",
        ),
        migrations.AlterModelOptions(
            name="profession",
            options={},
        ),
        migrations.AddField(
            model_name="profession",
            name="hot_history",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
