# Generated by Django 5.2.6 on 2025-12-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommend_profession",
            "0007_delete_professiontrend_alter_profession_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionTrend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("hot", models.IntegerField(verbose_name="热度值")),
                ("rank", models.IntegerField(default=0, verbose_name="年度排名")),
                (
                    "growth_rate",
                    models.FloatField(default=0.0, verbose_name="同比增长率(%)"),
                ),
                (
                    "employment_rate",
                    models.FloatField(default=0.0, verbose_name="就业率(%)"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="recommend_profession.profession",
                        verbose_name="关联专业",
                    ),
                ),
            ],
            options={
                "verbose_name": "专业趋势",
                "verbose_name_plural": "专业趋势",
                "ordering": ["-year"],
                "unique_together": {("profession", "year")},
            },
        ),
    ]
