# Generated by Django 5.2.6 on 2025-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_profession", "0008_professiontrend"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profession_type",
                    models.CharField(max_length=256, verbose_name="专业类别"),
                ),
                (
                    "profession_name",
                    models.CharField(max_length=256, verbose_name="专业名称"),
                ),
                ("popularity", models.IntegerField(verbose_name="人气值")),
            ],
            options={
                "verbose_name": "专业数据",
                "verbose_name_plural": "专业数据",
            },
        ),
        migrations.AlterModelOptions(
            name="profession",
            options={
                "ordering": ["id"],
                "verbose_name": "专业信息",
                "verbose_name_plural": "专业信息",
            },
        ),
        migrations.RemoveField(
            model_name="profession",
            name="hot_history",
        ),
        migrations.DeleteModel(
            name="ProfessionTrend",
        ),
    ]
