# Generated by Django 2.2.5 on 2019-11-19 08:53
# 导入Django迁移模块和模型字段模块
from django.db import migrations, models

# 定义迁移类，继承自Django的Migration基类，用于描述数据库结构的变更
class Migration(migrations.Migration):
#标识这是该 Django 应用的初始迁移文件，负责创建应用的第一个数据库表结构
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='re_school',   # 模型名称
            fields=[    # 定义模型的字段
                #id字段：自动增长的主键，Django默认会为模型添加该字段，这里显式定义
                ('id', models.AutoField(
                    auto_created=True,  #自动创建
                    primary_key=True,   #主键
                    serialize=False,    #不进行序列化
                    verbose_name='ID'   #显示名称
                    )),
                # school_name字段：字符类型，最大长度128
                ('school_name', models.CharField(max_length=128)),
                #学校所在省份：字符串类型，最大长度128
                ('school_province', models.CharField(max_length=128)),
                # 学校类型字段：字符类型，最大长度128
                ('student_type', models.CharField(max_length=128)),
                # 年份字段：字符类型，最大长度128
                ('year', models.CharField(max_length=128)),
                # 批次字段：字符类型，最大长度128
                ('epoch', models.CharField(max_length=128)),
                # 分数线字段：整数类型
                ('score_avg', models.IntegerField()),
                # 录取最低分字段：整数类型
                ('score_low', models.IntegerField()),
                # 省控线字段：整数类型
                ('score_province', models.IntegerField()),
            ],
            options={   # 模型的元数据选项
                'verbose_name': '专业信息', #模型的单数名称
                'verbose_name_plural': '专业信息',  #模型的复数名称
                'ordering': ['id'], #默认排序方式，按id字段升序排列
            },
        ),
    ]
