# Generated by Django 2.2.5 on 2019-11-24 12:57
# 导入Django迁移模块
from django.db import migrations

# 定义迁移类，继承自Django的Migration基类，用于描述数据库结构的变更
class Migration(migrations.Migration):
# 该迁移依赖于recommend_school应用的0001_initial迁移文件
    dependencies = [
        ('recommend_school', '0001_initial'),   # 依赖的应用和迁移文件
    ]
# 定义迁移操作列表
    operations = [
        migrations.DeleteModel(
            name='re_school',   # 要删除的模型名称
        ),
    ]
