# Generated by Django 5.2.6 on 2025-12-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_info", "0007_one_school_pictures"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=256, verbose_name="学校名称"),
                ),
                (
                    "profession_name",
                    models.CharField(max_length=256, verbose_name="专业名称"),
                ),
                ("student_type", models.CharField(max_length=32, verbose_name="科类")),
                ("year", models.IntegerField(verbose_name="年份")),
                ("highest_score", models.IntegerField(verbose_name="最高分")),
                ("avg_score", models.IntegerField(verbose_name="平均分")),
                ("lowest_score", models.IntegerField(verbose_name="最低分")),
                ("lowest_rank", models.IntegerField(verbose_name="最低排名")),
                ("epoch", models.CharField(max_length=32, verbose_name="批次")),
            ],
            options={
                "verbose_name": "录取数据",
                "verbose_name_plural": "录取数据",
            },
        ),
        migrations.AlterModelOptions(
            name="one_school",
            options={
                "ordering": ["id"],
                "verbose_name": "学校详细信息",
                "verbose_name_plural": "学校详细信息",
            },
        ),
        migrations.AlterModelOptions(
            name="school_info",
            options={
                "ordering": ["id"],
                "verbose_name": "学校基本信息",
                "verbose_name_plural": "学校基本信息",
            },
        ),
        migrations.AlterModelOptions(
            name="school_score",
            options={
                "ordering": ["id"],
                "verbose_name": "学校分数",
                "verbose_name_plural": "学校分数",
            },
        ),
    ]
