# Generated by Django 5.2.6 on 2025-12-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id"],
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
            },
        ),
    ]
