# Generated by Django 5.2.6 on 2025-12-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20191124_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="score",
            field=models.IntegerField(default=500),
        ),
    ]
